export const baseUrl = 'http://localhost:8080/'
export const registration = 'auth/register'
export const login = 'auth/login'
export const users = 'admin/users'
export const postsWithComments = 'posts/comments'
export const upload = 'upload'